//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fresh.Global.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fresh.Global.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gml=&quot;http://www.opengis.net/gml/3.2&quot; targetNamespace=&quot;http://www.isotc211.org/2005/gco&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://www.opengis.net/gml/3.2&quot; schemaLocation=&quot;referenceSystems.xsd&quot;/&gt;
        ///	&lt;xs:import name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string basicTypes {
            get {
                return ResourceManager.GetString("basicTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:census=&quot;http://release.niem.gov/niem/codes/census_uscounty/3.0/&quot; xmlns:structures=&quot;http://release.niem.gov/niem/structures/3.0/&quot; targetNamespace=&quot;http://release.niem.gov/niem/codes/census_uscounty/3.0/&quot; version=&quot;1&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://release.niem.gov/niem/structures/3.0/&quot; schemaLocation=&quot;structures.xsd&quot;/&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string census_uscounty {
            get {
                return ResourceManager.GetString("census_uscounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:core_misc=&quot;http://release.niem.gov/niem/codes/core_misc/3.0/&quot; xmlns:structures=&quot;http://release.niem.gov/niem/structures/3.0/&quot; targetNamespace=&quot;http://release.niem.gov/niem/codes/core_misc/3.0/&quot; version=&quot;1&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://release.niem.gov/niem/structures/3.0/&quot; schemaLocation=&quot;structures.xsd&quot;/&gt;
        ///	&lt;xs:anno [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string core_misc {
            get {
                return ResourceManager.GetString("core_misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot; xmlns:gmd=&quot;http://www.isotc211.org/2005/gmd&quot; xmlns:gts=&quot;http://www.isotc211.org/2005/gts&quot; xmlns:gsr=&quot;http://www.isotc211.org/2005/gsr&quot; xmlns:gss=&quot;http://www.isotc211.org/2005/gss&quot; targetNamespace=&quot;http://www.isotc211.org/2005/gmd&quot; elementFormDefault=&quot;qualified&quot; version=&quot;0.1&quot;&gt;
        ///	&lt;xs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dataQuality {
            get {
                return ResourceManager.GetString("dataQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:emevent=&quot;http://release.niem.gov/niem/domains/emergencyManagement/3.1/emevent/0.1/&quot; xmlns:mo=&quot;http://release.niem.gov/niem/domains/militaryOperations/3.2/&quot; xmlns:nc=&quot;http://release.niem.gov/niem/niem-core/3.0/&quot; xmlns:emcd=&quot;http://release.niem.gov/niem/domains/emergencyManagement/3.1/emevent/0.1/codes/&quot; xmlns:niem-xs=&quot;ht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string em_base {
            get {
                return ResourceManager.GetString("em_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:emcd=&quot;http://release.niem.gov/niem/domains/emergencyManagement/3.1/emevent/0.1/codes/&quot; xmlns:structures=&quot;http://release.niem.gov/niem/structures/3.0/&quot; targetNamespace=&quot;http://release.niem.gov/niem/domains/emergencyManagement/3.1/emevent/0.1/codes/&quot; elementFormDefault=&quot;qualified&quot; version=&quot;1&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string emcl {
            get {
                return ResourceManager.GetString("emcl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:niem-xs=&quot;http://release.niem.gov/niem/proxy/xsd/3.0/&quot; xmlns:emlc=&quot;http://release.niem.gov/niem/domains/emergencyManagement/3.1/emevent/0.1/emlc/&quot; xmlns:nc=&quot;http://release.niem.gov/niem/niem-core/3.0/&quot; xmlns:emcd=&quot;http://release.niem.gov/niem/domains/emergencyManagement/3.1/emevent/0.1/codes/&quot; xmlns:mo=&quot;http://release.ni [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string emlc {
            get {
                return ResourceManager.GetString("emlc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;EventTypeCodeList&gt;
        ///  &lt;EventTypeCode Value=&quot;ATOM&quot;&gt;ATOM&lt;/EventTypeCode&gt;
        ///  &lt;EventTypeCode Value=&quot;ATOM.AIRTRK&quot;&gt;AIR TRACK&lt;/EventTypeCode&gt;
        ///  &lt;EventTypeCode Value=&quot;ATOM.AIRTRK.CVL&quot;&gt;CIVIL AIRCRAFT&lt;/EventTypeCode&gt;
        ///  &lt;EventTypeCode Value=&quot;ATOM.AIRTRK.CVL.FIXD&quot;&gt;FIXED WING&lt;/EventTypeCode&gt;
        ///  &lt;EventTypeCode Value=&quot;ATOM.AIRTRK.CVL.FIXD.EM&quot;&gt;Emergency Fixed Wing&lt;/EventTypeCode&gt;
        ///  &lt;EventTypeCode Value=&quot;ATOM.AIRTRK.CVL.FIXD.EM.FIRE&quot;&gt;Fire Fixed Wing&lt;/EventTypeCode&gt;
        ///  &lt;EventTypeCode Value=&quot;ATOM.AI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventTypeCodeList {
            get {
                return ResourceManager.GetString("EventTypeCodeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:structures=&quot;http://release.niem.gov/niem/structures/3.0/&quot; xmlns:appinfo=&quot;http://release.niem.gov/niem/appinfo/3.0/&quot; xmlns:fema-rtlt=&quot;http://www.ptaccenter.org/Rtlt.Core.Api.V1&quot; xmlns:rtlt=&quot;http://example.com/adapters/fema_rtlt/3.0/&quot; targetNamespace=&quot;http://example.com/adapters/fema_rtlt/3.0/&quot; version=&quot;1&quot;&gt;
        ///	&lt;xs:import n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fema_rtlt {
            get {
                return ResourceManager.GetString("fema_rtlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:tns=&quot;http://www.ptaccenter.org/Rtlt.Core.Api.V1&quot; targetNamespace=&quot;http://www.ptaccenter.org/Rtlt.Core.Api.V1&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xs:element name=&quot;GetDisciplines&quot;&gt;
        ///		&lt;xs:complexType&gt;
        ///			&lt;xs:sequence/&gt;
        ///		&lt;/xs:complexType&gt;
        ///	&lt;/xs:element&gt;
        ///	&lt;xs:element name=&quot;GetDisciplinesResponse&quot;&gt;
        ///		&lt;xs:complexType&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fema_rtlt1 {
            get {
                return ResourceManager.GetString("fema_rtlt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:fips_10-4=&quot;http://release.niem.gov/niem/codes/fips_10-4/3.0/&quot; xmlns:structures=&quot;http://release.niem.gov/niem/structures/3.0/&quot; targetNamespace=&quot;http://release.niem.gov/niem/codes/fips_10-4/3.0/&quot; version=&quot;1&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://release.niem.gov/niem/structures/3.0/&quot; schemaLocation=&quot;structures.xsd&quot;/&gt;
        ///	&lt;xs:anno [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fips_10_4 {
            get {
                return ResourceManager.GetString("fips_10_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:fips_5-2=&quot;http://release.niem.gov/niem/codes/fips_5-2/3.0/&quot; xmlns:structures=&quot;http://release.niem.gov/niem/structures/3.0/&quot; targetNamespace=&quot;http://release.niem.gov/niem/codes/fips_5-2/3.0/&quot; version=&quot;1&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://release.niem.gov/niem/structures/3.0/&quot; schemaLocation=&quot;structures.xsd&quot;/&gt;
        ///	&lt;xs:annotat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fips_5_2 {
            get {
                return ResourceManager.GetString("fips_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:gml=&quot;http://www.opengis.net/gml/3.2&quot; xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot; xmlns:gss=&quot;http://www.isotc211.org/2005/gss&quot; targetNamespace=&quot;http://www.isotc211.org/2005/gss&quot; elementFormDefault=&quot;qualified&quot; version=&quot;0.1&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://www.opengis.net/gml/3.2&quot; schemaLocation=&quot;referenceSystems.xsd&quot;/&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string geometry {
            get {
                return ResourceManager.GetString("geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:structures=&quot;http://release.niem.gov/niem/structures/3.0/&quot; xmlns:appinfo=&quot;http://release.niem.gov/niem/appinfo/3.0/&quot; xmlns:xls=&quot;http://release.niem.gov/niem/external/ogc/xls/1.1.0/dhs-gmo/2.1.0&quot; xmlns:gml=&quot;http://www.opengis.net/gml/3.2&quot; xmlns:geo=&quot;http://release.niem.gov/niem/adapters/geospatial/3.0/&quot; targetNamespace=&quot;h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string geospatial {
            get {
                return ResourceManager.GetString("geospatial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:maid=&quot;http://release.niem.gov/niem/domains/emergencyManagement/3.1/emevent/0.1/maid/&quot; xmlns:niem-xs=&quot;http://release.niem.gov/niem/proxy/xsd/3.0/&quot; xmlns:emlc=&quot;http://release.niem.gov/niem/domains/emergencyManagement/3.1/emevent/0.1/emlc/&quot; xmlns:emcd=&quot;http://release.niem.gov/niem/domains/emergencyManagement/3.1/emevent/0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maid {
            get {
                return ResourceManager.GetString("maid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:niem-xs=&quot;http://release.niem.gov/niem/proxy/xsd/3.0/&quot; xmlns:nc=&quot;http://release.niem.gov/niem/niem-core/3.0/&quot; xmlns:mo=&quot;http://release.niem.gov/niem/domains/militaryOperations/3.2/&quot; xmlns:structures=&quot;http://release.niem.gov/niem/structures/3.0/&quot; xmlns:appinfo=&quot;http://release.niem.gov/niem/appinfo/3.0/&quot; xmlns:xls=&quot;http:// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mo {
            get {
                return ResourceManager.GetString("mo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:structures=&quot;http://release.niem.gov/niem/structures/3.0/&quot; xmlns:nc=&quot;http://release.niem.gov/niem/niem-core/3.0/&quot; xmlns:niem-xs=&quot;http://release.niem.gov/niem/proxy/xsd/3.0/&quot; xmlns:fips_10-4=&quot;http://release.niem.gov/niem/codes/fips_10-4/3.0/&quot; xmlns:census=&quot;http://release.niem.gov/niem/codes/census_uscounty/3.0/&quot; xmlns:fip [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string niem_core {
            get {
                return ResourceManager.GetString("niem_core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:gml=&quot;http://www.opengis.net/gml/3.2&quot; xmlns:xls=&quot;http://release.niem.gov/niem/external/ogc/xls/1.1.0/dhs-gmo/2.1.0&quot; targetNamespace=&quot;http://release.niem.gov/niem/external/ogc/xls/1.1.0/dhs-gmo/2.1.0&quot; elementFormDefault=&quot;qualified&quot; version=&quot;1.1.0&quot;&gt;
        ///	&lt;import namespace=&quot;http://www.opengis.net/gml/3.2&quot; schemaLocation=&quot;referenceSy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ols {
            get {
                return ResourceManager.GetString("ols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:gml=&quot;http://www.opengis.net/gml/3.2&quot; xmlns:gmd=&quot;http://www.isotc211.org/2005/gmd&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; targetNamespace=&quot;http://www.opengis.net/gml/3.2&quot; elementFormDefault=&quot;qualified&quot; version=&quot;3.2.1&quot;&gt;
        ///	&lt;import namespace=&quot;http://www.isotc211.org/2005/gmd&quot; schemaLocation=&quot;dataQuality.xsd&quot;/&gt;
        ///	&lt;import names [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string referenceSystems {
            get {
                return ResourceManager.GetString("referenceSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:gml=&quot;http://www.opengis.net/gml/3.2&quot; xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot; xmlns:gsr=&quot;http://www.isotc211.org/2005/gsr&quot; targetNamespace=&quot;http://www.isotc211.org/2005/gsr&quot; elementFormDefault=&quot;qualified&quot; version=&quot;0.1&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://www.opengis.net/gml/3.2&quot; schemaLocation=&quot;referenceSystems.xsd&quot;/&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spatialReferencing {
            get {
                return ResourceManager.GetString("spatialReferencing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:structures=&quot;http://release.niem.gov/niem/structures/3.0/&quot; targetNamespace=&quot;http://release.niem.gov/niem/structures/3.0/&quot; version=&quot;1&quot;&gt;
        ///	&lt;xs:attribute name=&quot;id&quot; type=&quot;xs:ID&quot;/&gt;
        ///	&lt;xs:attribute name=&quot;ref&quot; type=&quot;xs:IDREF&quot;/&gt;
        ///	&lt;xs:attribute name=&quot;metadata&quot; type=&quot;xs:IDREFS&quot;/&gt;
        ///	&lt;xs:attribute name=&quot;relationshipMetadata&quot; type=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string structures {
            get {
                return ResourceManager.GetString("structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:gml=&quot;http://www.opengis.net/gml/3.2&quot; xmlns:gco=&quot;http://www.isotc211.org/2005/gco&quot; xmlns:gts=&quot;http://www.isotc211.org/2005/gts&quot; targetNamespace=&quot;http://www.isotc211.org/2005/gts&quot; elementFormDefault=&quot;qualified&quot; version=&quot;0.1&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://www.opengis.net/gml/3.2&quot; schemaLocation=&quot;referenceSystems.xsd&quot;/&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string temporalObjects {
            get {
                return ResourceManager.GetString("temporalObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:unece=&quot;http://release.niem.gov/niem/codes/unece_rec20/3.0/&quot; xmlns:structures=&quot;http://release.niem.gov/niem/structures/3.0/&quot; targetNamespace=&quot;http://release.niem.gov/niem/codes/unece_rec20/3.0/&quot; version=&quot;1&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://release.niem.gov/niem/structures/3.0/&quot; schemaLocation=&quot;structures.xsd&quot;/&gt;
        ///	&lt;xs:anno [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unece_rec20_misc {
            get {
                return ResourceManager.GetString("unece_rec20_misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; targetNamespace=&quot;http://www.w3.org/1999/xlink&quot; version=&quot;2.0&quot;&gt;
        ///	&lt;annotation&gt;
        ///		&lt;appinfo source=&quot;urn:opengis:specification:gml:schema-xlinks:v3.0c2&quot;&gt;xlinks.xsd v3.0b2 2001-07&lt;/appinfo&gt;
        ///		&lt;documentation&gt;
        ///			GML 3.0 candidate xlinks schema. Copyright (c) 2001 OGC, All Rights Reserved.
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xlinks {
            get {
                return ResourceManager.GetString("xlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C XML Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:structures=&quot;http://release.niem.gov/niem/structures/3.0/&quot; xmlns:niem-xs=&quot;http://release.niem.gov/niem/proxy/xsd/3.0/&quot; targetNamespace=&quot;http://release.niem.gov/niem/proxy/xsd/3.0/&quot; version=&quot;1&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://release.niem.gov/niem/structures/3.0/&quot; schemaLocation=&quot;structures.xsd&quot;/&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xs {
            get {
                return ResourceManager.GetString("xs", resourceCulture);
            }
        }
    }
}
